FROM python:3.11

WORKDIR /app

# Копируем зависимости
COPY requirements.txt .

# Устанавливаем Python зависимости
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir pytest pytest-cov pytest-asyncio

# Копируем ВСЕ исходные файлы
COPY . .

# Создаем директорию для отчетов
RUN mkdir -p /app/reports

CMD ["pytest", "--cov=app", "-v"]